### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by uxkjaer** [Schoutenk/ui5-middleware-proxy-basicauth#1]
Great initiative. However you currently have a bug in your return of the getProxyUri. You are just returning true from the function and therefore the proxy isn't working. I changed it to uri.href and was able to load my metadata correctly.

**Comment by Schoutenk** [comment]
Thanks again for your fix in https://github.com/Schoutenk/ui5-middleware-proxy-basicauth/pull/2.
