### ISSUE TITLE
Wrong target url generation and wrong access to the client property

### ISSUE THREAD

**Issue by cgraff** [Schoutenk/ui5-middleware-proxy-basicauth#5]
Hi,

I found two other problems with the current client property handling, I'll pull shortly.

## Wrong client property access of the middleware configuration 

The client is part of the configuration of the middleware (`options.configuration.client`) but in line 52 (method *buildRequestUrl*) it is only accessed via `options.client`. This leads to target urls that contain a query param `sap-client=undefined`.

## Wrong target url building 

The current logic of `buildRequestUrl` generates faulty urls. 
If there is no `uri.query` present the 1st query param would be `sap-client` and therefore should start with `?sap-client` but is actually `&sap-client`. 

Cheers,
Christian :-)

**Comment by Schoutenk** [comment]
Hi @cgraff,
Thank you for giving your feedback. I've update the coding so these issues should be fixed.
