### ISSUE TITLE
Credentials in yaml file

### ISSUE THREAD

**Issue by rpanneel** [Schoutenk/ui5-middleware-proxy-basicauth#8]
Hi Koen,

I see that in your solution you set the credentials op a user in the .yaml-file. But this means that these credentials are stored in the git repo and available for everyone to see.

Isn't it a better option to add credentials in a .env file in the application and that the module checks these variables from there? 

For example:
```javascript
console.log(`Your port is ${process.env.PORT}`); // undefined
const dotenv = require('dotenv');
dotenv.config();
console.log(`Your port is ${process.env.PORT}`); // 8626
```

Then the .env file can be added to the .gitignore

But i'm not 100% sure that this would actually work. Do you see other options to remove the credentials from the yaml file?

Kind regards,

Robin

**Comment by cgraff** [comment]
Hi,
this is how I solved this issue atm. I've added a ui5-dev.yaml to my .gitignore file. In this file also credentials are stored and i run my ui5 server by using `ui5 serve --config ui5-dev.yaml` .
Of course the support of environment vars would be more convenient :-)

Best regards,
Christian

**Comment by rpanneel** [comment]
Hi Christian,

I'm not really a fan of having two .yaml files, but it will indeed get the job done also. 😄 
I got it locally solved with a .env file. But at my customer we don't have the authorizations to pull and push to github. So I will create a pull request this weekend.

Basically in the .env-file of your application you add the variables and the js-script reads them.

Kind regards,

Robin

**Comment by Schoutenk** [comment]
Great input guys. Thanks for your update.
